version: '2'
services:
  server:
    image: itzg/minecraft-server
    ports:
      - '25565:25565'
      - '8123:8123'
    volumes:
      - "./build/libs:/data/plugins:ro"
    environment:
      EULA: 'TRUE'
      VERSION: '1.11.2'
      TYPE: 'SPIGOT'